import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getSession } from "@/lib/get-session";
import Link from "next/link";
import { getSearchFromLibrary } from "../queries";
import { SearchQueryParams, SearchResultItem } from "../types";

interface SearchListProps {
  searchParams: Promise<SearchQueryParams>;
}

export default async function SearchList({ searchParams }: SearchListProps) {
  const session = await getSession();
  const { search } = await searchParams;

  if (!search?.trim()) {
    return (
      <div className="text-sm text-muted-foreground">
        Type something above to search through your library.
      </div>
    );
  }

  const results: SearchResultItem[] = await getSearchFromLibrary(
    session?.user.id as string,
    search,
  );

  if (results.length === 0) {
    return (
      <div className="text-sm text-muted-foreground">
        No results found for &ldquo;{search}&rdquo;.
      </div>
    );
  }

  return (
    <div className="space-y-4 pt-4">
      <p className="text-xs text-muted-foreground">
        Found {results.length} relevant items
      </p>
      {results.map((item) => (
        <Card
          key={item.id}
          className="transition-colors hover:border-primary/50"
        >
          <CardHeader className="pb-2">
            <div className="flex items-center justify-between">
              <Link href={`/library/${item.id}`} className="hover:underline">
                <CardTitle className="text-base font-semibold">
                  {item.title}
                </CardTitle>
              </Link>
              <Badge variant="outline" className="text-xs uppercase">
                {item.matchType}
              </Badge>
            </div>
            <p className="text-xs text-muted-foreground">{item.source}</p>
          </CardHeader>
          <CardContent>
            {/* Render highlighted snippet safely generated by PostgreSQL ts_headline */}
            <div
              className="text-sm leading-relaxed text-muted-foreground [&_mark]:rounded [&_mark]:bg-yellow-200 [&_mark]:px-0.5 [&_mark]:font-semibold [&_mark]:text-foreground [&_mark]:dark:bg-yellow-800/80"
              dangerouslySetInnerHTML={{ __html: item.snippet }}
            />
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
